[versions]
# Project
mod = "1.0.0"
java = "21"

# Minecraft / Fabric
minecraft = "1.21.11"
yarn-mappings = "1.21.11+build.4"
fabric-loader = "0.18.4"
fabric-loom = "1.15-SNAPSHOT"
fabric-api = "0.141.2+1.21.11"

# Paper
paper-api = "1.21.4-R0.1-SNAPSHOT"
shadow = "9.0.0-beta4"

# NeoForge
neoforge = "21.11.37-beta"
moddevgradle = "2.0.140"

# Libraries
configurate = "4.2.0"
kyori-option = "1.1.0"
geantyref = "2.0.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn-mappings = { module = "net.fabricmc:yarn", version.ref = "yarn-mappings" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
configurate-core = { module = "org.spongepowered:configurate-core", version.ref = "configurate" }
kyori-option = { module = "net.kyori:option", version.ref = "kyori-option" }
geantyref = { module = "io.leangen.geantyref:geantyref", version.ref = "geantyref" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
moddevgradle = { id = "net.neoforged.moddev", version.ref = "moddevgradle" }
