modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/jeppestaerk/Minecraft-Plugin-EventNotifications/issues"

[[mods]]
modId = "eventnotifications"
version = "${version}"
displayName = "EventNotifications"
authors = "Jeppe Staerk"
description = '''
Send real-time notifications to various targets (ntfy, Discord, Slack, webhooks) when server events occur.
'''

[[dependencies.eventnotifications]]
modId = "neoforge"
type = "required"
versionRange = "[21.11.0-beta,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.eventnotifications]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,1.21.12)"
ordering = "NONE"
side = "SERVER"
